controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
# test_email:
#     path: /test-email
#     controller: App\Controller\EmailController::sendTestEmail

email_gmail:
    path: /email-gmail
    controller: App\Controller\EmailController::sendEmail

